### ISSUE TITLE
Export FBX for UE4 causes error on Blender 3.2 or after

### ISSUE THREAD

**Issue by tomotaco** [Indie-us-Games/X4UE#3]
Expected result:
Exporting should succeed with no error.

Actual result:
Returns python errors:
```
Python: Traceback (most recent call last):
  File "C:\Users\tomot\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\x4ue\x4ue_export.py", line 125, in execute
    return X4UE_OT_export_fbx.execute(self, context)
  File "C:\Users\tomot\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\x4ue\x4ue_export.py", line 223, in execute
    if bpy.context.active_object.proxy:
AttributeError: 'Object' object has no attribute 'proxy'
```

**Comment by tomotacoiug** [comment]
Fixed by https://github.com/Indie-us-Games/X4UE/pull/4
